#!/bin/tcsh
#PBS -N asg:ex:mac-sa
#PBS -l nodes=6:xeon:compute:ppn=8
#PBS -l walltime=180:00:00
#PBS -j oe


cd $PBS_O_WORKDIR

mvp2run -m cyclic -c 48 python-mpi ../../../runscript.py /sciclone/home00/sgoodman/work/extracts/gen3.3/extract/ioe/macarthur/20160201_1454355259_79218_mac-sa/config.json
